export type ContentCard = { title: string; description: string; href?: string; status?: string };
export type ContentSection = { eyebrow?: string; title: string; body?: string[]; items?: string[]; cards?: ContentCard[]; notice?: string };
export type PublicPage = { eyebrow: string; metaTitle?: string; title: string; description: string; sections: ContentSection[]; cta: string; form?: "contact" | "audit" };

export const services: ContentCard[] = [
  { title: "Website Architecture", description: "Premium, conversion-focused websites designed around credibility, customer journeys, performance, accessibility, and future integration.", href: "/services/website-architecture" },
  { title: "Software Development", description: "Custom applications, portals, dashboards, operational tools, and software platforms engineered around real workflows.", href: "/services/software-development" },
  { title: "AI Systems", description: "Practical AI assistants, expert workflows, intelligent intake systems, document tools, and decision-support experiences with human oversight.", href: "/services/ai-systems" },
  { title: "Automation and Operations", description: "Connected workflows that reduce repetitive work, improve handoffs, organize information, and keep operations moving.", href: "/services/automation" },
  { title: "API and System Integration", description: "Architecture connecting websites, inventory, POS, CRM, accounting, payments, portals, and operational software.", href: "/services/api-integrations" },
  { title: "SaaS and Product Development", description: "A structured path from validated idea and product strategy through MVP architecture and launch readiness.", href: "/services/saas-development" },
  { title: "Mobile and App Experiences", description: "Responsive web applications, progressive web apps, and cross-platform experiences for customers, members, teams, and field operations.", href: "/services/mobile-apps" },
  { title: "Learning Platforms", description: "Custom LMS experiences, academies, creator systems, lesson workflows, progress tracking, and education operations.", href: "/services/learning-platforms" },
  { title: "Business Intelligence", description: "Operational dashboards, reporting environments, performance visibility, and decision-support systems designed around meaningful metrics.", href: "/services/business-intelligence" },
];

export const solutions: ContentCard[] = [
  { title: "Inventory and POS Integration", description: "Connect product discovery, inventory, sales, staff workflows, notifications, and reporting—subject to technical discovery.", href: "/solutions/inventory-pos-integration" },
  { title: "Customer Portals", description: "One clear place for requests, documents, status, appointments, resources, and support.", href: "/solutions/customer-portals" },
  { title: "Member Portals", description: "Private digital experiences organizing resources, communication, progress, and role-based access.", href: "/solutions/member-portals" },
  { title: "Learning Management", description: "Course delivery, lesson organization, assessments, resources, progress, and administration in one coherent system.", href: "/solutions/learning-management" },
  { title: "E-commerce and Ordering", description: "Commerce planned around inventory, payments, fulfillment, communication, staff review, and reporting.", href: "/solutions/ecommerce" },
  { title: "AI Assistants", description: "Assistants with approved knowledge, clear responsibilities, escalation rules, and transparent limitations.", href: "/solutions/ai-assistants" },
  { title: "Custom Dashboards", description: "Decision-focused visibility for work, exceptions, risk, progress, and meaningful operational measures.", href: "/solutions/custom-dashboards" },
  { title: "Business Operations Systems", description: "Structured workflows for intake, tasks, approvals, records, communication, scheduling, and follow-through.", href: "/solutions/business-operations" },
];

export const products: ContentCard[] = [
  { title: "TRUSTed Studio Hub", description: "A connected workspace concept for projects, assets, brand systems, AI direction, and specialized creation studios.", status: "In development" },
  { title: "TRUSTed Studio LMS", description: "A creator-focused learning platform for courses, lessons, readiness review, and learning-experience preparation.", status: "Private prototype" },
  { title: "TRUSTed LMS", description: "A learner-centered platform for course delivery, lesson progress, resources, and education workflows.", status: "In development" },
  { title: "TRUSTed PianoPath AI", description: "A visual, child-friendly piano-learning concept for guided practice, feedback, creativity, and parent visibility.", status: "Private prototype" },
  { title: "TRUSTed Vault OS", description: "A private operating-system concept for organized documents, workflows, tasks, reviews, and member resources.", status: "In development" },
  { title: "TRUSTed Dispatching", description: "An operations-platform concept for owner-operators, dispatch workflows, documentation, communication, and business visibility.", status: "Planned" },
];

export const processStages = [
  ["Discover", "Learn goals, users, operations, technology, pain points, constraints, and outcomes."],
  ["Audit", "Examine the current website, workflows, tools, integrations, content, data movement, and risks."],
  ["Strategize", "Define priority problems, business case, boundaries, success measures, and implementation path."],
  ["Architect", "Design system structure, user journeys, data relationships, integrations, permissions, and foundation."],
  ["Design", "Translate the architecture into a premium, accessible, clear, and responsive experience."],
  ["Develop", "Implement the approved product in controlled phases with maintainable, verifiable code."],
  ["Integrate", "Connect approved systems, APIs, data, automation, notifications, and workflows."],
  ["Test", "Validate functionality, responsiveness, accessibility, performance, reliability, and critical flows."],
  ["Launch", "Prepare production, deployment, documentation, training, and the launch plan."],
  ["Optimize", "Review verified outcomes, address friction, improve workflows, and plan the next stage."],
] as const;

const servicePage = (eyebrow: string, title: string, description: string, listTitle: string, items: string[], insightTitle: string, insight: string, cta: string): PublicPage => ({ eyebrow, metaTitle: eyebrow, title, description, sections: [{ title: listTitle, items }, { eyebrow: "Architecture First", title: insightTitle, body: [insight] }], cta });
const solutionPage = (title: string, description: string, items: string[], cta: string): PublicPage => ({ eyebrow: "Solution", title, description, sections: [{ eyebrow: "Common Capabilities", title: "Designed around the complete workflow.", items }, { title: "Discovery before commitment.", body: ["Final functionality depends on approved scope, platform access, technical feasibility, security requirements, and the systems already in use."] }], cta });

export const pages: Record<string, PublicPage> = {
  services: { eyebrow: "Services", title: "Digital architecture from strategy through implementation.", description: "TRUSTed Digital Architecture helps organizations plan, design, build, connect, and improve the digital systems that support their customers and operations.", sections: [{ title: "Core capabilities", cards: services }, { title: "One problem may require more than one discipline.", body: ["A customer portal may require website design, custom software, authentication planning, payment integration, automation, reporting, and ongoing support. We structure the work as one architecture rather than unrelated deliverables."] }], cta: "Discuss your project" },
  "services/website-architecture": servicePage("Website Architecture", "A website designed as part of your business—not apart from it.", "We design premium websites that communicate clearly, establish credibility, guide customers, perform reliably, and prepare your organization for future integrations.", "What we build", ["Corporate and professional-service websites", "E-commerce and membership experiences", "Landing pages and resource hubs", "Customer and client portals", "Product marketing sites", "Education and academy websites", "Multi-location and inventory-oriented websites"], "More than visual design.", "A successful website requires strategy, information architecture, content hierarchy, responsive behavior, accessibility, performance, search readiness, conversion logic, and technical discipline.", "Plan your website architecture"),
  "services/software-development": servicePage("Custom Software Development", "Software shaped around how your business actually works.", "When off-the-shelf tools create workarounds, duplicate entry, weak visibility, or fragmented experiences, custom software can create a cleaner operating model.", "What we build", ["Internal business applications", "Operational dashboards", "Customer and member portals", "Employee workspaces", "Workflow and scheduling systems", "Intake and case-management tools", "CRM and ERP extensions", "Custom administrative systems"], "Start with the workflow—not the feature list.", "We study who performs the work, what information they need, where delays occur, and which systems already contain the data.", "Discuss a custom software project"),
  "services/ai-systems": servicePage("AI Systems", "Practical AI built into controlled business workflows.", "We design AI-enabled experiences that help customers and teams search, understand, organize, draft, route, and act—while preserving appropriate human oversight.", "AI solution categories", ["Customer service and product-guidance assistants", "Inventory and parts-request assistants", "Intelligent intake", "Internal knowledge assistants", "Document classification and summarization", "Content and lesson-production workflows", "Website audit systems", "Workflow decision support"], "An AI assistant is only as useful as the system around it.", "Effective AI requires approved information sources, defined responsibilities, guardrails, escalation paths, auditability, user experience, and reliable integrations. AI outputs may contain errors and high-impact decisions require qualified human review.", "Explore an AI use case"),
  "services/automation": servicePage("Automation and Operations", "Reduce repetitive work without losing operational control.", "We design connected workflows that move information, trigger actions, route requests, create records, notify teams, and reduce unnecessary manual steps.", "Common use cases", ["Lead routing and customer intake", "Follow-up sequences and task creation", "Document collection and approvals", "Inventory and order-status notifications", "Proposal and invoice workflows", "CRM synchronization", "Reporting and alerts"], "Automate the process—not the confusion.", "We clarify workflow, ownership, exceptions, and data requirements before automating the stable parts.", "Identify automation opportunities"),
  "services/api-integrations": servicePage("API and System Integration", "Connect the systems your business already depends on.", "We architect secure, maintainable connections between websites, applications, inventory, POS, CRM, accounting, payment, communication, and reporting environments.", "Integration categories", ["Inventory and website synchronization", "Point-of-sale connections", "CRM and accounting integration", "Approved payment workflows", "Shipping and fulfillment", "Email and messaging", "Customer portals", "Analytics and reporting", "Webhooks and custom middleware"], "Technical discovery is required.", "Capabilities depend on vendor APIs, account ownership, documentation, permissions, security requirements, fees, rate limits, and support arrangements.", "Plan an integration discovery"),
  "services/saas-development": servicePage("SaaS and Product Development", "Turn a validated idea into a structured software product.", "We help define the product, users, value, workflows, technical boundaries, MVP, operating model, and path to launch readiness.", "Product stages", ["Opportunity and user discovery", "Product strategy", "Workflow and data architecture", "MVP definition", "Experience design", "Phased development", "Quality and launch readiness", "Optimization planning"], "Build the smallest product that proves the right thing.", "We separate essential validation from expensive assumptions and plan the product in controlled stages.", "Discuss a product idea"),
  "services/mobile-apps": servicePage("Mobile and App Experiences", "Useful product experiences wherever the work happens.", "We design responsive web applications, progressive web apps, and cross-platform experiences for customers, members, teams, and field operations.", "Capabilities", ["Customer and member apps", "Field and operations tools", "Mobile intake", "Scheduling and status", "Offline-aware experience planning", "Notifications", "Responsive dashboards", "Cross-device workflows"], "Choose the right delivery model.", "The best experience may be a responsive web app, PWA, or native application. Technical discovery determines the appropriate approach.", "Plan an app experience"),
  "services/learning-platforms": servicePage("Learning Platforms", "Build a complete operating environment for learning.", "We design platforms for course delivery, lesson production, resources, assessments, creator workflows, learner progress, and operational oversight.", "Platform categories", ["Learning management systems", "Online academies", "Course and creator platforms", "Parent-led learning", "Employee training", "Certification workflows", "Lesson and media production", "Learner dashboards", "Education administration"], "Learning is both an experience and an operation.", "We architect the learner journey together with the workflows required to create, review, deliver, and improve content.", "Plan a learning platform"),
  "services/business-intelligence": servicePage("Business Intelligence", "Turn operational data into usable visibility.", "We design dashboards and reporting systems that help leaders understand activity, identify risk, track progress, and make better decisions.", "Capabilities", ["Executive dashboards", "Operational metrics", "Inventory visibility", "Sales and service reporting", "Workflow bottlenecks", "Customer activity", "Project and team visibility", "Exception alerts", "Role-specific reporting"], "Measure what supports a decision.", "We prioritize useful signals and action over decorative statistics.", "Plan a reporting system"),
  solutions: { eyebrow: "Solutions", title: "Start with the business problem.", description: "Our services are technical disciplines. Our solutions combine those disciplines around specific operational and customer needs.", sections: [{ title: "Connected solutions", cards: solutions }], cta: "Find the right solution" },
  "solutions/inventory-pos-integration": { eyebrow: "Inventory and Point-of-Sale Integration", title: "Make inventory easier to find, request, sell, and manage.", description: "We help inventory-driven businesses plan connected experiences between their website, customers, staff, inventory platform, point-of-sale system, payments, notifications, and reporting.", sections: [{ title: "Ideal for inventory-driven organizations", items: ["Auto parts and equipment suppliers", "Manufacturers and wholesalers", "Retailers and multi-location sellers", "Specialty inventory businesses", "Organizations with complex catalogs"] }, { title: "Customer and staff possibilities", items: ["Search or filter inventory", "Submit structured product requests", "Confirm supported availability", "Route requests by category or location", "Prepare orders for staff review", "Trigger approved notifications", "Synchronize approved records", "Produce operational reporting"] }, { title: "Required technical discovery", items: ["Inventory or POS provider and account ownership", "API documentation and sandbox availability", "Data fields, permissions, and webhooks", "Security and payment limitations", "Vendor fees, usage limits, and support arrangements"], notice: "Actual capabilities depend on the client’s platform, API access, permissions, security requirements, and approved business rules." }], cta: "Request an inventory integration assessment" },
  "solutions/customer-portals": solutionPage("Give customers one clear place to work with your business.", "Customer portals can centralize requests, documents, orders, messages, payments, status, appointments, resources, and support.", ["Secure account-access planning", "Request submission", "Document upload", "Order and project status", "Scheduling", "Messaging", "Approved payment links", "Notifications and history"], "Plan a customer portal"),
  "solutions/member-portals": solutionPage("Private digital experiences for members, clients, and communities.", "We design member environments that organize content, resources, workflows, communication, progress, and role-based access.", ["Member resources", "Role-based experience planning", "Progress and activity", "Communication", "Private workflows", "Structured content"], "Plan a member experience"),
  "solutions/learning-management": solutionPage("A complete operating environment for structured learning.", "Combine course delivery, lesson organization, assessments, resources, learner progress, creator workflows, and administration in one coherent system.", ["Course and lesson delivery", "Assessments", "Learner progress", "Resources", "Creator workflows", "Administration"], "Plan your learning system"),
  "solutions/ecommerce": solutionPage("Commerce experiences connected to real operations.", "We plan e-commerce and ordering systems around products, inventory, payments, fulfillment, customer communication, staff review, and reporting.", ["Catalog architecture", "Inventory planning", "Ordering workflows", "Approved payments", "Fulfillment", "Customer communication", "Reporting"], "Discuss an ordering system"),
  "solutions/ai-assistants": solutionPage("AI assistants that understand their role.", "An effective assistant needs approved knowledge, clear responsibilities, reliable tools, escalation rules, and transparent limitations.", ["Customer support", "Product guidance", "Inventory requests", "Intake", "Internal knowledge", "Education", "Content production", "Operational assistance"], "Define an AI assistant"),
  "solutions/custom-dashboards": solutionPage("See what requires attention.", "We design dashboards that prioritize meaningful decisions, open work, exceptions, risk, and progress—not decorative statistics.", ["Open work", "Exceptions and risk", "Operational progress", "Inventory visibility", "Customer activity", "Role-specific decisions"], "Plan a dashboard"),
  "solutions/business-operations": solutionPage("Bring fragmented operations into one structured workflow.", "We design operational systems for intake, tasks, approvals, records, communication, scheduling, documents, reporting, and follow-through.", ["Intake and routing", "Tasks and approvals", "Records and documents", "Scheduling", "Communication", "Reporting and follow-through"], "Map your operations"),
  products: { eyebrow: "TRUSTed Product Lab", title: "Software initiatives shaped by real operational problems.", description: "TRUSTed Product Lab explores education, creative production, private workspaces, business operations, and AI-enabled workflows. These initiatives are at different stages and are not offered as finished products.", sections: [{ title: "Product initiatives", cards: products }], cta: "Discuss a partnership or early-access interest" },
  industries: { eyebrow: "Industries", title: "Technology designed around industry reality.", description: "Every industry has different workflows, terminology, risks, customer expectations, systems, and compliance obligations. We adapt the architecture accordingly.", sections: [{ title: "Industries we serve", cards: [
    ["Automotive and Parts", "Inventory search, part requests, POS integration planning, ordering, and operational visibility."], ["Professional Services", "Lead intake, client portals, scheduling, documents, workflows, and reporting."], ["Education", "Learning platforms, course production, learner dashboards, administration, and resources."], ["Healthcare", "Information, intake, scheduling, and administrative planning with strict privacy and compliance review."], ["Finance", "Client experiences, document workflows, reporting, intake, and automation under security and regulatory constraints."], ["Technology", "Product sites, SaaS applications, dashboards, onboarding, support, integrations, and operations."], ["Manufacturing", "Catalogs, inventory visibility, ordering, dashboards, documentation, and integration."], ["Logistics", "Dispatch, communication, documentation, scheduling, visibility, and workflow automation."], ["Construction", "Lead intake, estimates, project portals, scheduling, field workflows, and documents."], ["Real Estate", "Property experiences, lead routing, client portals, document workflows, and reporting."], ["E-commerce", "Catalogs, inventory, ordering, payments, customer service, fulfillment, and analytics."], ["Nonprofits and Ministries", "Public websites, resources, membership, learning, communications, and operations."],
  ].map(([title, description]) => ({ title, description })) }], cta: "Discuss your industry" },
  process: { eyebrow: "Our Process", title: "A transparent architecture and delivery process.", description: "The process reduces ambiguity, protects scope, validates critical assumptions, and produces a system that can be maintained after launch.", sections: [{ title: "Ten disciplined stages", cards: processStages.map(([title, description], index) => ({ title: `${String(index + 1).padStart(2, "0")} — ${title}`, description })) }, { title: "Engagement structures", cards: [{ title: "Discovery Engagement", description: "For unclear or technically complex projects." }, { title: "Defined Project", description: "For a clearly scoped website, application, integration, or platform." }, { title: "Phased Build", description: "For larger systems delivered through controlled milestones." }, { title: "Ongoing Architecture Partnership", description: "For continued optimization, maintenance, and strategic development." }] }], cta: "Begin with discovery" },
  about: { eyebrow: "About TRUSTed", title: "Architecture before accumulation.", description: "TRUSTed Digital Architecture exists to help organizations build technology with greater clarity, integrity, and long-term usefulness.", sections: [{ title: "Understand the system first.", body: ["Businesses are often told to buy more tools. We believe the better starting point is to understand the people, information, decisions, workflows, risks, and customer experience."] }, { title: "What makes TRUSTed different", cards: [{ title: "Systems Thinking", description: "We examine how the full business operates rather than isolating each deliverable." }, { title: "Practical Innovation", description: "We use modern technology where it creates real value—not because it is fashionable." }, { title: "Honest Architecture", description: "We identify limitations, dependencies, risks, and unknowns before making promises." }, { title: "Premium Execution", description: "We pursue clarity, usability, performance, maintainability, and refined presentation." }, { title: "Long-Term Alignment", description: "We design foundations that can evolve as the organization grows." }] }, { title: "Founder-led responsibility", body: ["TRUSTed Digital Architecture is founder-led and supported by a disciplined, AI-enabled planning and development process. Specialized tools and expert workflows may assist research, architecture, design, development, and quality review, while responsibility for client commitments remains human-led."] }], cta: "Start a conversation" },
  contact: { eyebrow: "Contact", title: "Tell us what needs to work better.", description: "You do not need a complete technical specification. Describe the business, the problem, the current systems, and the result you are trying to create.", sections: [{ title: "Request a project review", notice: "This public form is a non-functional intake preview. Use the email link to contact TRUSTed. Submitting a future form will not create a client relationship or guarantee project acceptance." }], cta: "Email TRUSTed", form: "contact" },
  "website-audit": { eyebrow: "Website Audit", title: "See your website through an architectural lens.", description: "Submit your current website for a structured review of clarity, credibility, user experience, performance, accessibility, conversion paths, content hierarchy, technical readiness, and integration opportunities.", sections: [{ title: "Audit categories", items: ["Positioning and messaging", "Navigation and information architecture", "Visual credibility", "Mobile experience", "Accessibility and performance", "Search readiness", "Conversion paths", "Security observations", "Integration readiness", "AI and automation opportunities"], notice: "This interface is a non-functional prototype until a secure intake, storage, and analysis workflow is approved. No automated review is performed." }], cta: "Email to request an audit", form: "audit" },
  privacy: { eyebrow: "Legal", title: "Privacy notice.", description: "This public marketing website does not provide accounts, payments, uploads, or approved persistent lead storage.", sections: [{ title: "Current data handling", body: ["The guided assessment stores non-contact business answers and recent display messages in this browser’s session storage so the virtual architect can persist across internal navigation. Closing the browser session or starting a new assessment clears that working state. Contact fields are not written to browser storage.", "Free-form AI messages and structured assessment context are sent to OpenAI for response generation with provider response storage disabled by this application. Visitors must not submit passwords, API keys, payment data, health information, legal secrets, or confidential business information.", "The local lead workflow validates information but does not claim persistent storage or email delivery. Production collection remains disabled until secure server-side storage, a confirmed notification provider, retention rules, and recovery procedures are approved."], notice: "This notice is informational and requires qualified privacy and legal review before production activation of AI or lead collection." }], cta: "Contact TRUSTed" },
  terms: { eyebrow: "Legal", title: "Website terms.", description: "This website describes services, concepts, product initiatives, and preliminary planning outputs for general informational purposes.", sections: [{ title: "Important limitations", body: ["Website content, an assessment, blueprint, estimate, or submission does not create a client relationship, guarantee project acceptance, or promise technical feasibility, pricing, results, integrations, or product availability. Commitments are confirmed only through written agreement after discovery.", "AI responses and preliminary assessments may contain errors and are not legal, medical, financial, safety, security, accessibility-certification, SEO, or compliance advice. The assistant cannot confirm appointments, email delivery, project approval, or authorization to begin work."], notice: "These terms require qualified legal review before production activation of AI or lead collection." }], cta: "Contact TRUSTed" },
};

export const primaryNavigation = [
  ["Services", "/services"], ["Solutions", "/solutions"], ["Products", "/products"], ["Industries", "/industries"], ["Process", "/process"], ["About", "/about"], ["Contact", "/contact"],
] as const;
